general {
    no_fade_in = false
    grace = 0
    disable_loading = false
}

# This creates a blurred slice on the left side
background {
    path =  /home/bamblurboo/.config/wallpaper/34.jpg
    blur_passes = 1 # High blur for that glass look
    blur_size = 3
    noise = 0.01
    contrast = 0.89
    brightness = 0.3
    vignette = 0.1
    vignette_darkness = 0.5
    # This crops the background to act as a panel
    zindex = 0
}

# PANEL OVERLAY (Tinting the blur)
shape {
    size = 600, 100%
    color = rgba(255, 255, 255, 0.05)
    rounding = 0
    position = 0, 0
    halign = left
    valign = center
}

# USER AVATAR
image {
    path = /home/bamblurboo/.config/wallpaper/Profile/rize.jpg
    size = 240
    rounding = -1
    border_size = 2
    border_color = rgba(0, 44, 116, 0.5)
    position = 180, 180 
    halign = left
    valign = center
    shadow_passes = 2
}

# USERNAME & WELCOME
label {
    monitor =
    # Combined the labels for cleaner alignment
    text = Bambalinaq # <span weight="light">$USER</span> 
    color = rgba(255, 255, 255, 0.8)
    font_size = 20
    font_family = Noto Serif CJK JP Medium
    position = 220, 10
    halign = left
    valign = center
    shadow_passes = 1
}

# TEXT
label {
    monitor =
    # Combined the labels for cleaner alignment
    text = ようこそ # <span weight="bold">$USER</span> |   
    color = rgba(255, 255, 255, 0.8)
    font_size = 48
    font_family = Noto Serif CJK JP Medium
    position = 180, 370
    halign = left
    valign = center
    shadow_passes = 1
}

# INPUT FIELD
input-field {
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 20
    placeholder_text = <span foreground="##ffffff99">Enter Password</span>
    hide_input = false
    position = 150, -60
    halign = left
    valign = center
}

# CLOCK
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 0.8)
    font_size = 80
    font_family = Noto Serif CJK JP Medium
    position = -125, 0
    halign = right
    valign = center
    shadow_passes = 2
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(255, 255, 255, 0.6)
    font_size = 20
    font_family = Noto Serif CJK JP Medium
    position = -125, -80 # Lowered below the clock
    halign = right
    valign = center
}